### ISSUE TITLE
Flip time as settings

### ISSUE THREAD

**Issue by kklimek** [marcinsaj/Flipo-Clock-4x7-Segment-Flip-Disc-Display#1]
Would be nice to have flip time configurable without recompiling and reuploading firmware. Could be stored in eeprom

**Comment by marcinsaj** [comment]
I will add this option. Thanks for the idea.

**Comment by marcinsaj** [comment]
24-Hour Clock with Flip-disc Speed/Delay Settings - using eeprom: https://github.com/marcinsaj/Flipo-Clock-4x7-Segment-Flip-Disc-Display/blob/main/examples/08-Classic-Clock-24-Hour-Flip-Speed.ino

12-Hour Clock ... : https://github.com/marcinsaj/Flipo-Clock-4x7-Segment-Flip-Disc-Display/blob/main/examples/10-Classic-Clock-12-Hour-Flip-Speed.ino

Settings Instruction: https://bit.ly/4x7SEG-CLOCK-SPEED-SET
