### ISSUE TITLE
Firmware Update

### ISSUE THREAD

**Issue by AlexHedley** [marcinsaj/Flipo-Clock-4x7-Segment-Flip-Disc-Display#2]
When in Arduino should the Board be **Arduino Nano Every**?

What should the **baud** rate be (9600)?

Is there a setup guide with the steps to do once you've put the device together?

**Comment by marcinsaj** [comment]
Getting started with Arduino
https://docs.arduino.cc/software/ide-v2/tutorials/getting-started-ide-v2/

- https://www.arduino.cc/en/software - choose the version for MAC or Windows, just download and install.
- Open Arduino IDE
- Sketch -> Include Library -> Manage Libraries
- In Library Manager type "FlipDisc.h" - install library
- Open https://github.com/marcinsaj/Flipo-Clock-4x7-Segment-Flip-Disc-Display/blob/main/examples/01-Basic-Test.ino - copy code
- File -> New Sketch - delete sample code and paste code from point 4 in this file.
- Tools -> Board -> Arduino megaAVR Boards -> Arduino Nano Every
- Tools -> Port -> set Arduino Nano Every port
- Turn OFF the clock
- Connect clock via USB
- Sketch -> Upload
- Wait (even 60 seconds) until you see on bottom right "Upload completed"
- Disconnect USB cable
- Turn ON the clock

Let me know if you need any more help.

**Comment by AlexHedley** [comment]
Thanks :)

**Comment by AlexHedley** [comment]
![image](https://github.com/user-attachments/assets/5bf4820a-20cc-4e70-965e-98816eecae7f)
![image](https://github.com/user-attachments/assets/b93ae76a-1d5d-4f18-ad06-bd685dc9e263)
![image](https://github.com/user-attachments/assets/cdbbcc32-776f-4195-ae21-d328a514f621)
![image](https://github.com/user-attachments/assets/c7f7369b-9001-452b-9b54-ac4e70c3146e)

**Comment by AlexHedley** [comment]
![image](https://github.com/user-attachments/assets/97975a55-c519-46cd-84af-4fcc2ae924ad)

**Comment by AlexHedley** [comment]
Have you come across this error before?

```bash
avrdude: jtagmkII_initialize(): Cannot locate "flash" and "boot" memories in description
avrdude: jtagmkII_reset(): timeout/error communicating with programmer (status -1)
avrdude: initialization failed, rc=-1
         Double check connections and try again, or use -F to override
         this check.

avrdude: jtagmkII_close(): timeout/error communicating with programmer (status -1)
avrdude: jtagmkII_close(): timeout/error communicating with programmer (status -1)
Failed uploading: uploading error: exit status 1
```

![image](https://github.com/user-attachments/assets/929ea262-30c6-481b-ae2f-487cb4335b4a)

**Comment by AlexHedley** [comment]
> if you have a multimeter, I suggest checking that the display connectors are properly soldered and there are no short circuits before connecting the power supply.

**Comment by marcinsaj** [comment]
@AlexHedley check that you have selected the correct COM port.

**Comment by AlexHedley** [comment]
![image](https://github.com/user-attachments/assets/1f9edcd1-2b45-4305-986e-d25cd33324e2)

![image](https://github.com/user-attachments/assets/5b9f47c5-1614-4d8f-8e85-c577ecf6add8)
![image](https://github.com/user-attachments/assets/38fb35cd-ce46-42cf-b055-781c07059b11)

**Comment by marcinsaj** [comment]
@AlexHedley 
I assume you have the latest Arduino IDE.
Remove the Arduino board from the controller.
Try upload Blink sketch. If it works, try uploading the clock code until it works.
Check if the USB cable is OK and try with another one.
