### ISSUE TITLE
Examples with OneButton lib don't currently compile

### ISSUE THREAD

**Issue by keyboard-magpie** [marcinsaj/Flipo-Clock-4x7-Segment-Flip-Disc-Display#3]
Using onebutton v2.6.1 causes compilation issues. Dropping back to 2.0.0 seems to resolve this. Can you clarify which versioning you are using in the code comments please :)

**Comment by keyboard-magpie** [comment]
Testing further, 2.5.0 is the latest OneButton lib that seems to work.

**Comment by keyboard-magpie** [comment]
Saying all this, i've just reinstalled it and it's behaving now. Odd. Will close.

**Comment by marcinsaj** [comment]
@keyboard-magpie I have version 2.6.1 - everything works fine.
