### ISSUE TITLE
"typo" on final clock code instructions

### ISSUE THREAD

**Issue by keyboard-magpie** [marcinsaj/Flipo-Clock-4x7-Segment-Flip-Disc-Display#4]
<img width="577" alt="Screenshot 2024-08-15 at 20 12 38" src="https://github.com/user-attachments/assets/fe2b6e5e-d75c-4891-8156-60c5d8221fd0">

Small mislabelling here, should be bottom button as you know.

Lovely example code!

**Comment by marcinsaj** [comment]
Thank you, I corrected it.
